[package]
name = "dataset-handling"
version = "0.1.0"
edition = "2021"

[dependencies]
calamine = "0.20"
csv = "1.1"
chrono = "0.4"
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
