.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp
temp

.DS_Store
*.log
*.local

docker
dataset-handling
prisma
*.csv
*.sql
*.xlsx

apps/*
!apps/frontend
!apps/frontend/**
