export const MIN_OCCURRENCE_YEAR = 2013;
export const MIN_OCCURRENCE_DATE_ISO = `${MIN_OCCURRENCE_YEAR}-01-01`;
export const MIN_OCCURRENCE_DATE = new Date(
  `${MIN_OCCURRENCE_DATE_ISO}T00:00:00.000Z`
);
